sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "9"
cache: npm
  
branches:
  only:
  - master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli

# use stages to make pipeline clear
stages:
  - name: UT
  - name: e2e
  - name: build
  - name: release
    
jobs:
  include:
    - stage: UT
      script:
        - ng lint
        - ng test --watch=false --browsers=ChromeHeadless

    - stage: e2e
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        - ng e2e

    - stage: build
      script:
        - ng build --prod --base-href https://artificerpi.github.io/tour-of-heroes/
        - "for lang in zh-CN; do
              ng build --aot --prod --i18n-file src/locale/messages.$lang.xlf 
                --i18n-format xlf --i18n-locale $lang --output-path=dist/$lang 
                --base-href https://artificerpi.github.io/tour-of-heroes/$lang/;
          done"

    - stage: release
      script:
        deploy:
          provider: pages
          skip_cleanup: true
          # read $GITHUB_TOKEN from travis-ci config
          github_token: $GITHUB_TOKEN
          local_dir: dist/
          on:
            branch: master